name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Завантажити код
        uses: actions/checkout@v2

      - name: Виконати тести
        run: npm test